name: Deployment

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    
    - name: Sync
      env:
              dest: '${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:/var/www/html/wordpress/wp-content/'
      run: |
        sudo echo "${{secrets.SERVER_SSH_KEY}}" > deploy_key
        sudo chmod 600 ./deploy_key
        sudo rsync -chav \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /README.md \
          --exclude /node_modules/ \
          --exclude /script.sh/ \
          ./ ${{env.dest}}
          
    - name: Set Permissions and Ownership
  run: |
    # Change permissions recursively for the deployed files
    sudo chmod -R 755 ${{env.dest}}
    
    # Change ownership recursively for the deployed files
    sudo chown -R ${{secrets.SERVER_WP}} ${{env.dest}}

    
    - name: Restart Nginx
      run: |
          sudo systemctl restart nginx

    
   






