name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 12.x
    
    - name: Sync
      env:
              dest: '${{secrets.SERVER_USERNAME}}@${{secrets.SERVER_HOST}}:/var/www/html/wordpress/wp-content/theme'
      run: |
        sudo echo "${{secrets.SERVER_SSH_KEY}}" > deploy_key
        sudo chmod 600 ./deploy_key
        sudo rsync -chav \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /README.md \
          --exclude /node_modules/ \
          ./ ${{env.dest}}
